name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          ###### Repository/Build Configurations ######
          app_location: "/" # Update if the HTML files are not in the root directory, e.g., 'src' # App source code path (update if necessary, depending on the folder where index.html is located)
          api_location: "" # Api source code path - optional
          output_location: "" # Leave empty for simple static HTML sites, or specify if there is a build output folder # Built app content directory - optional
          app_build_command: "" # No build command required for static HTML site
          deployment_action: "upload" # Specify the deployment action
          deployment_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # Add the deployment token for authorization
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
